Object.defineProperty(exports, "__esModule", { value: true });
exports.EVENT_TYPES = {
    FILE_ADDED: 'FILE_ADDED',
    FILE_UPDATED: 'FILE_UPDATED',
    FILE_REMOVED: 'FILE_REMOVED',
    DIR_ADDED: 'DIR_ADDED',
    DIR_UPDATED: 'DIR_UPDATED',
    DIR_REMOVED: 'DIR_REMOVED'
};
exports.FILE_ADDED = exports.EVENT_TYPES.FILE_ADDED;
exports.FILE_UPDATED = exports.EVENT_TYPES.FILE_UPDATED;
exports.FILE_REMOVED = exports.EVENT_TYPES.FILE_REMOVED;
exports.DIR_ADDED = exports.EVENT_TYPES.DIR_ADDED;
exports.DIR_UPDATED = exports.EVENT_TYPES.DIR_UPDATED;
exports.DIR_REMOVED = exports.EVENT_TYPES.DIR_REMOVED;
