export const EVENT_TYPES = {
    FILE_ADDED: 'FILE_ADDED',
    FILE_UPDATED: 'FILE_UPDATED',
    FILE_REMOVED: 'FILE_REMOVED',
    DIR_ADDED: 'DIR_ADDED',
    DIR_UPDATED: 'DIR_UPDATED',
    DIR_REMOVED: 'DIR_REMOVED'
}

export const FILE_ADDED = EVENT_TYPES.FILE_ADDED
export const FILE_UPDATED = EVENT_TYPES.FILE_UPDATED
export const FILE_REMOVED = EVENT_TYPES.FILE_REMOVED
export const DIR_ADDED = EVENT_TYPES.DIR_ADDED
export const DIR_UPDATED = EVENT_TYPES.DIR_UPDATED
export const DIR_REMOVED = EVENT_TYPES.DIR_REMOVED